### PR TITLE
Update Dockerfile to use SeaweedFS 1.80

### LINKED ISSUE #3: arm64 support
Everything is available, just appropriate packages need to be referend (seaweedfs's arm64 package)

### LINKED ISSUE #4: bump seaweedfs to 1.80
by initial manual testing, it seems that volume creation with bumped version seems to work well

### PR DESCRIPTION
**Pull request by chrislusf**

### CODE REVIEW

**Comment by zicklag** [comment]
This looks great but could you squash the commits before I merge it?

**Comment by psukys** [comment]
you can link #3 and #4 to this PR

**Comment by zicklag** [comment]
Done. :+1:

**Comment by chrislusf** [comment]
squash and merge should be one option when you merge.

**Comment by zicklag** [comment]
I know, but I don't like merge commits, so I prefer to squash them and then rebase them onto master. For some reason, "Squash and Rebase" is not an option. :man_shrugging:

**Comment by chrislusf** [comment]
I could not get git sqush to work. Got error "patch contents already upstream" when git pull before git push.

**Comment by zicklag** [comment]
Try `git push --force` and don't attempt to `git pull` before pushing.

**Comment by zicklag** [comment]
Perfect, that worked. Sorry to trouble you, but it does wonders for the git commit history. Thanks for the update! :smiley:

**Comment by zicklag** [comment]
@psukys I also pushed a new build of the plugin for amd64 to DockerHub with the `latest` tag and the `git-8824b6fd` tag if you want a specific plugin version.

**Pull request merged**
