### PR TITLE
Make the plugin work again

### LINKED ISSUE #7: Volumes being created even when seaweedfs is not running
I reinstalled the plugin yesterday evening, and since then, I have been able to create volumes using this plugin even when I have not started seaweedfs server and the volumes remain visible even after stopping seaweedfs server. Also, the volumes aren't visible when I access filer through localhost:8888.

### PR DESCRIPTION
**Pull request by nivekuil**
Fix #7 

Really I'm not sure if the title is accurate -- either this plugin never worked to begin with or I'm still missing something.

### CODE REVIEW

**Comment by nivekuil** [comment]
Actually I see this repo made the same change to get it working, so at least @SvenDowideit has been using the bulk of the code here without too much issue?  https://github.com/onaci/docker-plugin-seaweedfs/blob/golang/Dockerfile

**Comment by zicklag** [comment]
Hey there! Fair warning, I don't use the plugin anymore and I'm not sure what state it is in. It was made to experiment with SeaweedFS, but we @katharostech didn't actually end up using it.

I'm happy to merge your PR if it helps it work for other people who may try this out, though!

If you got this working for you, then great, but you may want to actually try out the `onaci/docker-plugin-seaweedfs` plugin because it probably gets a bit more love than this one. Either way, thanks for the PR!

**Comment by nivekuil** [comment]
No, I don't think it quite works even after some more digging.  Probably best to archive this repo or add a big disclaimer that it appears to be broken.

**Comment by zicklag** [comment]
I'll update the README. Thanks for the tip.

**Comment by SvenDowideit** [comment]
hmmmm, yes, we use it, and it works well until etcd gets confused. I'm still looking around for something that "just works" but i'm not that hopeful :)

**Comment by nivekuil** [comment]
@SvenDowideit yeah, etcd is why I am a little shy about trying your repo. Since you wrote that seaweedfs filers are able to do active-active replication themselves now: https://github.com/chrislusf/seaweedfs/wiki/Filer-Active-Active-cross-cluster-continuous-synchronization that's what I was planning on trying.

**Comment by SvenDowideit** [comment]
ok, that's excellent to read - January, for sure!

**Comment by SvenDowideit** [comment]
My _main_ use for this, is config files that are (rarely) modified - for example, prometheus config files generated by other containers to tell prometheus to scrape them
having those cfg files on all nodes means i don't need to care if a node dies, or a container gets re-started elsewhere

**Comment by nivekuil** [comment]
Prometheus added Docker Swarm service discovery recently too, so I think your use case is entirely automated at this point and you can just pass around static configs :)

**Pull request merged**
